import numpy as np
a=np.array([3,6,7,8,9])
print("the array is:",a)
sum=np.sum(a)
print("the sum is:",sum)
avg=np.mean(a)
print("the average is:",avg)
min=np.min(a)
print("the minimum value is:",min)
max=np.max(a)
print("the maximum value is:",max)
imin=np.argmin(a)
print("the index of minimum value:",imin)
imax=np.argmax(a)
print("the index of maximum value:",imax)
std=np.std(a)
print("standard deviation:",std)
var=np.var(a)
print("varience:",var)
mid=np.median(a)
print("median value:",mid)
